name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy to EC2 with SSM

    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'

    runs-on: ubuntu-latest

    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::181185361491:role/SSMDeployPolicy
          aws-region: ap-south-1

      - name: Deploy application through SSM
        run: |
          aws ssm send-command \
            --instance-ids i-05256d8c841e0f2ba \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "set -e",
              "echo Starting deployment...",
              "echo Pulling latest Docker image...",
              "docker pull ghcr.io/abhmrya/cicd-python-demo:latest",
              "echo Stopping old container...",
              "docker stop cicd-python-demo || true",
              "echo Removing old container...",
              "docker rm cicd-python-demo || true",
              "echo Starting new container...",
              "docker run -d --name cicd-python-demo --restart unless-stopped -p 8000:8000 ghcr.io/abhmrya/cicd-python-demo:latest",
              "echo Waiting for application...",
              "sleep 5",
              "echo Testing health endpoint...",
              "curl --fail http://localhost:8000/health",
              "echo Deployment successful!"
            ]' \
            --comment "Deploy cicd-python-demo"